server:
  port: 8040

spring:
  application:
    name: EMPLOYEE
  profiles:
    active:
      - dev
  zipkin:
    sender:
      type: RABBIT
  sleuth:
    sampler:
      probability: 0.1
  cloud:
    bus:
      destination: zipkin
      id: emp
#  activemq:
#    broker-url: http://localhost:15672
#    user: guest
#    password: guest
#    base-url: http://localhost:9411/
#    locator:
#      discovery:
#        enabled: true
#    service:
#      name: zipkinserver
#    sender:
#      type: RABBIT

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
    instance-info-replication-interval-seconds: 10
#  instance:
#    lease-renewal-interval-in-seconds: 1

management:
  endpoints:
    web:
      exposure:
        include:
          - hystrix.stream

logging:
  level:
    org.springframework: error

