spring:
  application:
    name: EMPLOYEE
  zipkin:
    base-url: http://localhost:9411/
#    locator:
#      discovery:
#        enabled: true
#    service:
#      name: zipkinserver
  sleuth:
    sampler:
      probability: 1

server:
  port: 8040

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
    instance-info-replication-interval-seconds: 10
#  instance:
#    lease-renewal-interval-in-seconds: 1

management:
  endpoints:
    web:
      exposure:
        include:
          - hystrix.stream

logging:
  level:
    org.springframework: debug

